# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOYy5Fv__cs5fjQ8sivaJpVdbljh0t1D
"""
#q1
for i in range(1,5):
    for j in range(1,5):
        print("*",end=" ")
    print()
#q2
for i in range(1,5):
    for j in range(1,i+1):
        print(j,end=" ")
    print()
#q3
for i in range(1,5):
    for j in range(1,i+1):
        print("*",end=" ")
    print()
#q4
k = 1
for i in range(1,4):
    for j in range(1,k+1):
        print("*",end=" ")
    k+=2
    print()
#q5
for i in range(1,5):
    for j in range(1,i+1):
        print(j,end=" ")
    print()
#q6
for i in range(1,5):
    for j in range(1,1+i):
        print(i,end=" ")
    print()
#q7
num =4
for i in range(1,5):
    for j in range(1,i+1):
        print(num,end=" ")
    num -=1
    print()
#q8
num = 1
for i in range(1,5):

    for j in range(1,i+1):
        print(num,end=" ")

        num +=1
    print()
#q9
num = 10
for i in range(1,5):
    for j in range(1,i+1):
        print(num,end=" ")
        num-=1
    print()
#q10
num = 1
for i in range(1,5):
    for j in range(1,i+1):
        print(num,end=" ")
        num+=2
    print()
#q11
num = 2
for i in range(1,5):
    for j in range(1,i+1):
        print(num,end=" ")
        num+=2
    print()
#q12
for i in range(1,5):
    x = 4
    for j in range(5,i,-1):
        print(x,end=" ")
        x-=1
    print()
#q13
for i in range(1,5):
    num = i
    for j in range(4,i-1,-1):
        print(num,end=" ")
    print()
#q14
for i in range(1,5):
    num = 1
    for j in range(5,i,-1):
        print(num,end=" ")
        num+=1
    print()