# -*- coding: utf-8 -*-
"""Untitled67.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXb3aY4snFkUyh1_dwPVdmJJvgc6HDA-
"""

class vechicle:
    company = "maruti"

class marutiev(vechicle):
    price = 100000
me1=marutiev()
print(me1.price,me1.company)

class vechicle:
    company = "maruti"
    def minfo(self):
        print("vechile class info function")

class marutiev(vechicle):
    price = 100000
    def minfo(self):
        super().minfo()
me1=marutiev()
print(me1.price,me1.company)
me1.minfo()

class vechicle:
    company = "maruti"
    def minfo(self):
        print("vechile class info function")

class marutiev(vechicle):
    price = 100000
    def minfo(self):
        super().minfo()
me1=marutiev()
print(me1.price,me1.company)
me1.minfo()

class parentTata:
    def __init__(self,mid,name):
        self.mid=mid
        self.name=name
class childTata(parentTata):
    def __init__(self,a,b):
        super().__init__(a,b)
obj = childTata(101, "Virendra")

print(obj.mid)
print(obj.name)

class parentTata:
    def __init__(self, mid, name):
        self.mid = mid
        self.name = name

class childTata(parentTata):
    def __init__(self, a, b):
        super().__init__(a, b)

obj = childTata(101, "Virendra")

print(obj.mid)
print(obj.name)

class parentTata:
    def __init__(self, mid, name):
        self.mid = mid
        self.name = name

    def info(self):
        print("parentclass",self.mid,self.name)

class childTata(parentTata):
    def __init__(self, a, b):
        super().__init__(a, b)
    def info(self):
        print("childclass",self.mid,self.name)
    def choice(self):
        super().info()

class childTata(parentTata):
    def __init__(self, a, b):
        super().__init__(a, b)
    def info(self):
        print("childclass",self.mid,self.name)
    def choice(self):
        super().info()